export const insumos = [
    {produto: "ABACAXI", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "ACAFRAO", unid: "KG", tipo: "MERCEARIA"},
    {produto: "ACUCAR CRISTAL 1KG", unid: "FRD", tipo: "MERCEARIA"},
    {produto: "ACUCAR MASCAVO", unid: "FRD", tipo: "MERCEARIA"},
    {produto: "ÁGUA DE COCO 300ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "ÁGUA MINERAL C/ GÁS - 500ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "AGUA MINERAL S/ GÁS - 500ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "ALCOOL GEL", unid: "UND", tipo: "LIMPEZA"},
    {produto: "ALFACE", unid: "UND", tipo: "HORTIFRUTI"},
    {produto: "ALHO", unid: "KG", tipo: "MERCEARIA"},
    {produto: "ALHO PORO", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "AMACIANTE DE CARNE 1,1KG", unid: "UND", tipo: "MERCEARIA"},
    {produto: "ARROZ", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "BACON CUBOS", unid: "KG", tipo: "FRIOS"},
    {produto: "BALDES", unid: "UND", tipo: "LIMPEZA"},
    {produto: "BATATA INGLESA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "BISTECA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "BERINJELA", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "BOBINA TÉRMICA", unid: "CX", tipo: "DIVERSOS"},
    {produto: "BUDWEISER LONG NECK", unid: "FRD", tipo: "CERVEJAS"},
    {produto: "BIS CHOCOLATE", unid: "PCT", tipo: "MERCEARIA"},
    {produto: "BISNAGA CHOC/BRANCO 1,01KG", unid: "CX", tipo: "MERCEARIA"},
    {produto: "BISNAGA CHOC/LEITE 1,01KG", unid: "CX", tipo: "MERCEARIA"},
    {produto: "BISNAGA DE DOCE DE LEITE 1,01KG", unid: "UND", tipo: "MERCEARIA"},
    {produto: "CAFE", unid: "UND", tipo: "MERCEARIA"},
    {produto: "CAJU LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "CAJUÍNA 500ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "CAJUÍNA LATA GERALDO 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "CANELA EM PÓ", unid: "PCT", tipo: "MERCEARIA"},
    {produto: "CARNE C/ OSSO", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CARNE MOÍDA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CARNE NA ROLA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CARNE P/ BIFE", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CARNE P/ MARIA ISABEL", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CAIXA PIZZA G", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "CAIXA PIZZA M", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "CAIXA PIZZA P", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "CAIXA PIZZA PP", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "CENOURA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CEBOLA BRANCA", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "CEBOLA ROXA", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "CEBOLINHA", unid: "UND", tipo: "HORTIFRUTI"},
    {produto: "CHAMPIGNON", unid: "UND", tipo: "MERCEARIA"},
    {produto: "CHEDDAR", unid: "CX", tipo: "FRIOS"},
    {produto: "CHOC. GRANULADO", unid: "UND", tipo: "MERCEARIA"},
    {produto: "CLORO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "COPO DESCARTAVEL 180ML", unid: "PCT", tipo: "DIVERSOS"},
    {produto: "COENTRO", unid: "UND", tipo: "HORTIFRUTI"},
    {produto: "CORANTE", unid: "KG", tipo: "MERCEARIA"},
    {produto: "CORONA LONG NECK 330ML", unid: "FRD", tipo: "CERVEJAS"},
    {produto: "COSTELA BOVINA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "COSTELA SUÍNA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "CREAM CHEESE", unid: "CX", tipo: "FRIOS"},
    {produto: "CREME CULINÁRIO", unid: "CX", tipo: "MERCEARIA"},
    {produto: "COCA COLA 1L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA 2L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA 600ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA ZERO 1L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA ZERO 2L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA ZERO 600ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "COCA COLA ZERO LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "DELICIA PAULISTA", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "DETERGENTE 5L", unid: "UND", tipo: "LIMPEZA"},
    {produto: "DESENGORDURANTE", unid: "UND", tipo: "LIMPEZA"},
    {produto: "DESINFETANTE PARA ÁREA ALIMENTÍCIA", unid: "UND", tipo: "LIMPEZA"},
    {produto: "DESINFETANTE USO GERAL", unid: "UND", tipo: "LIMPEZA"},
    {produto: "ERVILHA", unid: "UND", tipo: "MERCEARIA"},
    {produto: "ESPREMEDOR DE LIMÃO", unid: "UN", tipo: "DIVERSOS"},
    {produto: "FANTA LARANJA LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "FANTA UVA LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "FEIJÃO BRANCO", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "FEIJÃO CARIOCA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "FEIJÃO PRETO", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "FILÉ DE FRANGO", unid: "CX", tipo: "CONGELADOS"},
    {produto: "FRANGO INTEIRO", unid: "UND", tipo: "ALIMENTAÇÃO"},
    {produto: "GUARANÁ 1L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "GUARANÁ 2L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "GUARANÁ 600ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "GUARANÁ LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "GUARANÁ LATA ZERO 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "GUARANÁ ZERO 1L", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "HEINEKEN LONG NECK 330ML", unid: "FRD", tipo: "CERVEJAS"},
    {produto: "H2O LIMÃO", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "H2O LIMONETO", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "IMPERIO LONG NECK", unid: "FRD", tipo: "CERVEJAS"},
    {produto: "LIQUIDIFICADOR", unid: "UND", tipo: "PRODUÇÃO"},
    {produto: "LOMBO CANADENSE", unid: "UND", tipo: "FRIOS"},
    {produto: "MACA", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "MACAXEIRA", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "MARGARINA 1KG", unid: "UND", tipo: "MERCEARIA"},
    {produto: "MESINHAS P/ PIZZA", unid: "PCT", tipo: "DIVERSOS"},
    {produto: "MILHO VERDE", unid: "UND", tipo: "MERCEARIA"},
    {produto: "MOLHO BARBECUE", unid: "UND", tipo: "MERCEARIA"},
    {produto: "MOLHO P/ PIZZA", unid: "CX", tipo: "MERCEARIA"},
    {produto: "MOLHO SHOYU", unid: "UND", tipo: "MERCEARIA"},
    {produto: "NATA", unid: "UND", tipo: "MERCEARIA"},
    {produto: "OLEO SOJA 900ML", unid: "UND", tipo: "MERCEARIA"},
    {produto: "OREGANO 250G", unid: "UND", tipo: "MERCEARIA"},
    {produto: "OREGANO 500G", unid: "UND", tipo: "MERCEARIA"},
    {produto: "OVOS", unid: "CRT", tipo: "MERCEARIA"},
    {produto: "PEITO DE FRANGO", unid: "CX", tipo: "CONGELADOS"},
    {produto: "PEITO DE PERU", unid: "UND", tipo: "FRIOS"},
    {produto: "PEPERONI 1KG", unid: "KG", tipo: "FRIOS"},
    {produto: "PIMENTA BIQUINHO BALDE 2KG", unid: "UND", tipo: "MERCEARIA"},
    {produto: "PIMENTA TABASCO 600ML", unid: "UND", tipo: "MERCEARIA"},
    {produto: "PIMENTAO VERDE", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "PIMENTINHA", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "PLASTICO FILME", unid: "UN", tipo: "DIVERSOS"},
    {produto: "PONTAS DE CALABRESA", unid: "KG", tipo: "FRIOS"},
    {produto: "PAPEL BANDEJA", unid: "UND", tipo: "DIVERSOS"},
    {produto: "PAPEL TOALHA", unid: "UND", tipo: "LIMPEZA"},
    {produto: "RUCULA", unid: "UND", tipo: "HORTIFRUTI"},
    {produto: "SAL 1KG", unid: "FRD", tipo: "MERCEARIA"},
    {produto: "STELLA ARTOIS 330ML", unid: "FRD", tipo: "CERVEJAS"},
    {produto: "SODA LIMONADA LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "SONHO DE VALSA", unid: "PCT", tipo: "MERCEARIA"},
    {produto: "SPATEN LONG NECK 355ML", unid: "FRD", tipo: "CERVEJAS"},
    {produto: "SCHEWEPPS LATA 350ML", unid: "FRD", tipo: "BEBIDAS"},
    {produto: "TOMATE", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "TOMATE CEREJA BANDEJA", unid: "UND", tipo: "MERCEARIA"},
    {produto: "TOMATE SECO", unid: "UND", tipo: "MERCEARIA"},
    {produto: "TOSCANA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "VINAGRE BALSAMICO 500ML", unid: "UND", tipo: "MERCEARIA"},
    {produto: "VASSOURAS", unid: "UND", tipo: "LIMPEZA"},
    {produto: "REPOLHO", unid: "UND", tipo: "HORTIFRUTI"},
    {produto: "RODOS", unid: "UND", tipo: "LIMPEZA"},
    {produto: "SALSINHA", unid: "UND", tipo: "HORTIFRUTI"},
    {produto: "SACHE KETCHUP", unid: "CX", tipo: "DIVERSOS"},
    {produto: "SACHE MAIONESE", unid: "CX", tipo: "DIVERSOS"},
    {produto: "SACHE MOSTARDA", unid: "CX", tipo: "DIVERSOS"},
    {produto: "SACOS DE LIXO DIVERSOS TAMANHOS", unid: "UND", tipo: "LIMPEZA"},
    {produto: "SACO 1KG", unid: "PCT", tipo: "DIVERSOS"},
    {produto: "SACO 2KG", unid: "PCT", tipo: "DIVERSOS"},
    {produto: "SACO ADESIVO", unid: "PCT", tipo: "DIVERSOS"},
    {produto: "SACO P/ MASSA", unid: "UND", tipo: "DIVERSOS"},
    {produto: "ST PIETRO CAIXA G", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "ST PIETRO CAIXA M", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "ST PIETRO CAIXA P", unid: "UND", tipo: "EMBALAGENS"},
    {produto: "TAÇAS DE VIDRO", unid: "CX", tipo: "DIVERSOS"},
    {produto: "TOMATE", unid: "KG", tipo: "HORTIFRUTI"},
    {produto: "TRIGO AMARELA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "TRIGO BRANCA", unid: "KG", tipo: "ALIMENTAÇÃO"},
    {produto: "ÁGUA SANITÁRIA", unid: "UND", tipo: "LIMPEZA"},
    {produto: "ALCOOL 70 POR CENTO EM GEL", unid: "UND", tipo: "LIMPEZA"},
    {produto: "ALCOOL 70 POR CENTO LÍQUIDO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LUVAS DE LIMPEZA", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LIMPADOR DE PISO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LIMPADOR MULTIUSO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LIMPA-FORNO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LIMPA INOX", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LIMPADOR DE VIDRO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "LUSTRA MÓVEIS", unid: "UND", tipo: "LIMPEZA"},
    {produto: "MOP", unid: "UND", tipo: "LIMPEZA"},
    {produto: "PANOS DE CHÃO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "PANOS MULTIUSO", unid: "UND", tipo: "LIMPEZA"},
    {produto: "PÁS", unid: "UND", tipo: "LIMPEZA"},
    {produto: "SABÃO EM PÓ", unid: "UND", tipo: "LIMPEZA"},
    {produto: "SABÃO LÍQUIDO", unid: "UND", tipo: "LIMPEZA"}
  ];

  